services:
  - type: web
    name: cinedna
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: TMDB_READ_TOKEN
        sync: false
